const storyData=[
    {
        image:"https://static.javatpoint.com/blog/images/who-invented-instagram.png",
        name:"Kevin_systrom"
    },
    {
        image:"https://content.fortune.com/wp-content/uploads/2022/02/Satya-Nadella-Microsoft-CEO-Most-Admired.jpg",
        name:"Sathya_nadella"
    },
    {
        image:"https://variety.com/wp-content/uploads/2021/07/elon-musk-apple-app-store.jpg?w=681&h=383&crop=1",
        name:"Elon_musk"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/commons/1/18/Mark_Zuckerberg_F8_2019_Keynote_%2832830578717%29_%28cropped%29.jpg",
        name:"Mark_zuckerberg"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/commons/7/7e/Virat_Kohli.jpg",
        name:"Virat_kohli"
    },
    {
        image:"https://szcdn.ragalahari.com/aug2021/hd/varshini-sounderajan-hi-life-exhibition-aug2021/varshini-sounderajan-hi-life-exhibition-aug2021thumb.jpg",
        name:"Varshini"
    },
    {
        image:"https://cdn.vox-cdn.com/thumbor/L-F7i2dHys6QZZimr-KqNhfjLmU=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22450864/1232269483.jpg",
        name:"Cristiano_Ronaldo"
    },
    {
        image:"https://waynekspear.files.wordpress.com/2014/02/jankoum_1260.jpg",
        name:"Jan_koum"
    },
    {
        image:"https://english.sakshi.com/visual-stories/fashion/2021-10-21/6_1634785968.jpg",
        name:"Prabhas"
    },
    {
        image:"https://i.pinimg.com/736x/a6/26/ce/a626ce274bc4a14923a3eddaeadd95a0.jpg",
        name:"Sudheer"
    },
    {
        image:"https://wallpaperaccess.com/full/1685014.jpg",
        name:"Justin_Bieber"
    },
    {
        image:"https://static.toiimg.com/photo/82540178/Soon-to-be-mommy-Shreya-Ghoshal-flaunts-her-baby-bump-in-this-new-picture.jpg",
        name:"Shreya_Ghoshal"
    }

]
export default storyData